### ISSUE TITLE
New Feature Ideas

### ISSUE THREAD

**Issue by Aveek-Saha** [Aveek-Saha/DuskPlayer#30]
I am looking for new feature ideas for Dusk Player, keeping in line with the projects goal for being a minimalist Music Player.

If you want to contribute, please raise a new issue and if you want to work on it as well, wait for me to assign it to you. Once assigned, create a new Pull Request with your changes.

**Comment by michielst** [comment]
A feature I would want is a dynamic playlist directory.

This would mean that whenever a new song has been added to the filePath directory. Dusk Player would pick up on it and append it to the songs list withouth having to reopen the application.

**Comment by Aveek-Saha** [comment]
This could be useful, could you open a new issue with the feature request template?

**Comment by Green-Thanos** [comment]
Also, could we save playlists? Like you could set a playlist to a directory folder on your computer with all the music files.

**Comment by Abdallah-Moh** [comment]
@Aveek-Saha a whole new better UI without a menu bar using svelte-spa-router
