### ISSUE TITLE
When I try to build the app require is not defiend

### ISSUE THREAD

**Issue by Abdallah-Moh** [Aveek-Saha/DuskPlayer#53]
**Describe the bug**
When I try building from source I get the app empty and when I read the console get required is not defined

**To Reproduce**
Build the app from source

**Environment information:**
 - OS: Pop_!Os : Linux Distro
 - Application Version: source

**Comment by Aveek-Saha** [comment]
Please fill in the template and list the steps required to reproduce this bug
