### ISSUE TITLE
Few Features

### ISSUE THREAD

**Issue by messagebeliever2022** [Aveek-Saha/DuskPlayer#68]
This would work well on local as well as internet/hosted in server

#1 - Is it possible to add import song option -> title, song name, singer, lyrics, file (mp3 or m4a)
#2 - Is it possible to provide search song by any word in lyrics content or song name or song type
#3 - Possible to provide equalizer support

Example
https://stackoverflow.com/questions/34854976/write-a-preamp-with-html5-audio-api
https://codepen.io/Merevy/pen/egYrmB
https://github.com/bitgapp/eqMac

Thanks

**Comment by Aveek-Saha** [comment]
It is already possible to "import" a song, all you need to do is copy the file to the folder you are currently playing from and it'll show up in the playlist.

Features 2 and 3 are outside the scope of this project.
